from distutils.core import setup

setup(
    name='bitcoincrawler',
    version='',
    packages=['virtualenv.lib.python3.4.site-packages.aiohttp', 'virtualenv.lib.python3.4.site-packages.chardet',
              'virtualenv.lib.python3.4.site-packages.requests',
              'virtualenv.lib.python3.4.site-packages.requests.packages',
              'virtualenv.lib.python3.4.site-packages.requests.packages.chardet',
              'virtualenv.lib.python3.4.site-packages.requests.packages.urllib3',
              'virtualenv.lib.python3.4.site-packages.requests.packages.urllib3.util',
              'virtualenv.lib.python3.4.site-packages.requests.packages.urllib3.contrib',
              'virtualenv.lib.python3.4.site-packages.requests.packages.urllib3.packages',
              'virtualenv.lib.python3.4.site-packages.requests.packages.urllib3.packages.ssl_match_hostname',
              'virtualenv.lib.python3.4.site-packages.httpretty',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip.vcs',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip._vendor',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.distlib',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.distlib._backport',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.colorama',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.html5lib',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.html5lib.trie',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.html5lib.filters',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.html5lib.serializer',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.html5lib.treewalkers',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.html5lib.treeadapters',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.html5lib.treebuilders',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.requests',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.requests.packages',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.requests.packages.chardet',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.requests.packages.urllib3',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.requests.packages.urllib3.util',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.requests.packages.urllib3.contrib',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.requests.packages.urllib3.packages',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip._vendor._markerlib',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip.commands',
              'virtualenv.lib.python3.4.site-packages.pip-1.5.6-py3.4.egg.pip.backwardcompat', 'bitcoincrawler',
              'bitcoincrawler.test', 'bitcoincrawler.components', 'bitcoincrawler.components.bitcoind'],
    url='',
    license='',
    author='mirko',
    author_email='',
    description=''
)
